const SESSION_INIT = 'SESSION_INIT';
const SESSION_FETCH_SUCCESS = 'SESSION_FETCH_SUCCESS';
const SESSION_FETCH_ERROR = 'SESSION_FETCH_ERROR';

export default {
  SESSION_INIT,
  SESSION_FETCH_SUCCESS,
  SESSION_FETCH_ERROR
}